import Head from "next/head";
import React from "react";
import Loader from "../components/Loader";
import LazyLoadComponent from "../components/LazyLoadComponent";
import dynamic from "next/dynamic";

const SliderComponent = dynamic(() => import("../components/SliderComponent"), {
  loading: () => <Loader />,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev1"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev2"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev3"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev4"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev5"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev6"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev7"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev8"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev9"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev10"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev11"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev12"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev13"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev14"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev15"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev16"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev17"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev18"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev19"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev20"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev21"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev22"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev23"}/>} />
      <LazyLoadComponent  Component={<SliderComponent addClass={"dev24"}/>} />
     
    </>
  );
}
